torchrun \
 	--nproc_per_node $GPUS run_speech_recognition_seq2seq_peft.py \
	--deepspeed="deepspeed_configs/ds_config_zero2.json" \
	--model_name_or_path="openai/whisper-large-v3" \
	--dataset_name=$data \
	--dataset_config_name=$data_config \
	--train_split_name=$train_subset \
	--eval_split_name=$eval_subset \
	--max_steps="10000" \
	--output_dir="./whisper-large-librispeech-peft-16bit-max10000-lr1e-4-batch64" \
	--gradient_accumulation_steps="1" \
	--per_device_train_batch_size="32" \
	--per_device_eval_batch_size="32" \
	--logging_steps="25" \
	--learning_rate="1e-4" \
	--warmup_steps="500" \
	--evaluation_strategy="steps" \
	--eval_steps="5000" \
	--save_strategy="steps" \
	--save_steps="1000" \
	--generation_max_length="225" \
	--length_column_name="input_length" \
	--max_duration_in_seconds="30" \
	--ddp_timeout "86400" \
	--freeze_feature_encoder "False" \
	--audio_column_name=$audio_column_name \
	--text_column_name=$text_column_name \
	--preprocessing_num_workers=$num_proc \
	--language="english" \
	--preprocessing_only="False" \
	--group_by_length \
	--fp16 \
	--overwrite_output_dir \
	--do_train \
	--predict_with_generate \
	--use_auth_token
